service:
  enabled: true
env:
  APP_NAME: api-app
resources:
  requests:
    memory: 256Mi
    cpu: 50m
  limits:
    memory: 512Mi
    cpu: 150m
startupProbe:
  httpGet:
    path: /api/health-check/liveness
    port: 8080
  initialDelaySeconds: 90
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
livenessProbe:
  httpGet:
    path: /api/health-check/liveness
    port: 8080
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /api/health-check/readiness
    port: 8080
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
