import { config } from 'src/constants';

export const MESSAGING_ENTITY_CONFIG = {
  SCHEMAS_DIR: 'avro-schemas',
  PUBLISH_TOPICS: {
    IMAGE_PROCESSING: {
      TOPIC_NAME: config.QUEUE.IMAGE_PROCESSING_TOPIC_NAME,
      DLQ_REQUIRED: true,
      PARTITIONS: config.QUEUE.IMAGE_PROCESSING_TOPIC_PARTITIONS,
      DLQ_TOPIC_NAME: config.QUEUE.IMAGE_PROCESSING_DLQ_TOPIC_NAME,
      DLQ_PARTITIONS: config.QUEUE.IMAGE_PROCESSING_DLQ_TOPIC_PARTITIONS,
    },
  },
  CONSUMER_GROUP_ID: {
    IMAGE_PROCESSING: config.QUEUE.IMAGE_PROCESSING_CONSUMER_GROUP_ID,
  },
};
