kafka:
  image:
    repository: confluentinc/cp-kafka
    tag: 7.2.1
  replicaCount: 1
  resources:
    requests:
      memory: 768Mi
      cpu: 250m
    limits:
      memory: 1536Mi
      cpu: 500m
  env:
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
    KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
    KAFKA_PROCESS_ROLES: "broker,controller"
    KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092"
    KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs/data"
    KAFKA_JMX_PORT: "9997"
    KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=$(POD_NAME).kafka0-service.default.svc.cluster.local -Dcom.sun.management.jmxremote.rmi.port=9997"
schemaRegistry:
  image:
    repository: confluentinc/cp-schema-registry
    tag: 7.2.1
  replicaCount: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 512Mi
      cpu: 150m
  env:
    SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-0.kafka.kafka.svc.cluster.local:29092"
    SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
    SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "http"
    SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
    SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
kafkaUi:
  image:
    repository: provectuslabs/kafka-ui
    tag: v0.7.2
  replicaCount: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 512Mi
      cpu: 150m
  env:
    KAFKA_CLUSTERS_0_NAME: kafka
    KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-0.kafka.kafka.svc.cluster.local:29092
    KAFKA_CLUSTERS_0_METRICS_PORT: 9997
    KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://kafka-schema-registry-0.kafka-schema-registry.kafka.svc.cluster.local:8085
    # DYNAMIC_CONFIG_ENABLED: "true"
    KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED: "true"
    KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED: "true"
