export const providers = {
  REPOSITORIES: {
    REQUEST: 'REQUESTS_REPOSITORY',
  },
  ENTITIES: {
    CSV_VALIDATION: 'CSV_VALIDATION_ENTITY',
    MESSAGING: 'MESSAGING_ENTITY',
    IMAGE_PROCESSING_MESSAGING: 'IMAGE_PROCESSING_MESSAGING_ENTITY',
  },
  SERVICES: {
    CONFIGURATION: 'CONFIGURATION_SERVICE',
    LOGGER: 'LOGGER_SERVICE',
    DB: 'DB_SERVICE',
    REPOSITORY: 'REPOSITORY_SERVICE',
    QUEUE: 'QUEUE_SERVICE',
  },
  MODULES: {
    IMAGE_PROCESSOR: 'IMAGE_PROCESSOR_SERVICE',
  },
} as const;
