apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    app: kafka
  ports:
    - name: client-ext
      protocol: TCP
      port: 9092
      targetPort: 9092

    - name: client-int # Internal client port
      protocol: TCP
      port: 29092
      targetPort: 29092

    - name: controller # Controller port
      protocol: TCP
      port: 29093
      targetPort: 29093

    - name: jmx
      protocol: TCP
      port: 9997
      targetPort: 9997
  clusterIP: None
