apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-schema-registry"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    app: "{{ .Release.Name }}-schema-registry"
  ports:
    - protocol: TCP
      name: http
      port: 8085
      targetPort: 8085
  clusterIP: None
